version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  weather-service:
    build:
      context: ./weather_service
    ports:
      - "5000:5000"

  http-server:
    image: "${DOCKER_USERNAME}/http-server:${GITHUB_SHA}"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: usersdb
    depends_on:
      - db
      - weather-service

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - http-server

volumes:
  pgdata:
