name: CI
run-name: ${{ github.actor }} run CI
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - run: sudo apt-get update
    - run: sudo apt-get install g++ make cmake
    - run: sudo apt-get install -y libboost-all-dev
    
    - run: cd client && mkdir -p build && cd build && cmake .. && make && cd ../../server && mkdir -p build && cd build && cmake .. && make
    - run: cd ../..
    
    - run: sh create_debpkg_client.sh
    - name: Upload client artifact
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: ./client/http-client.deb
        
    - run: sh create_debpkg_server.sh
    - name: Upload server artifact
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: ./server/http-server.deb
        
    - name: Test 1. Install client
      run: sudo dpkg -i ./client/http-client.deb
      
    - name: Test 2. Test client
      run: echo "6" | libhv-client
      
    - name: Test 3. Install server
      run: sudo dpkg -i ./server/http-server.deb